### PR TITLE
avoid custom CreationalContext and Contextual implementations in the TCK

### PR DESCRIPTION
**Pull request by Ladicek**
On a small number of places, the CDI TCK creates its own implementations of `CreationalContext` and `Contextual`. These are extremely bare APIs that aren't sufficient for internal needs of CDI implementations or for interoperability. All CDI implementations that I know expose internally a much richer API and generally expect that their `CreationalContext` and `Contextual` implementations are used. It is possible to bend the implementations to accept a `CreationalContext` or `Contextual` of outside provenance, but I believe there's exactly nothing in the CDI specification that makes this mandatory.

Instead, I believe the CDI TCK should:

1. avoid using its own `CreationalContext` and `Contextual` implementations;
2. expose SPIs that lets implementations supply their own `CreationalContext` and `Contextual` implementations, augmented with inspection capabilities for the tests that need it.

This PR does exactly that.

### CODE REVIEW

**Comment by Ladicek** [comment]
Since this PR adds a new TCK SPI, this can only be done in the next major/minor CDI TCK version (4.1/5.0 I believe). Hence this is a draft for now.

**Comment by Ladicek** [comment]
I actually have a few more things locally, to avoid custom `Contextual`s in addition to custom `CreationalContext`s. I'll rebase and force-push to this PR.

**Comment by Ladicek** [comment]
Rebased, force-pushed, added a commit that removes obsolete TCK exclusions, and updated the title and summary of this PR.

@manovotn my implementation of these SPIs for Weld is in https://github.com/Ladicek/weld-core/commits/new-tck-spi, feel free to steal that :-) I also have an implementation of these SPIs for ArC on a branch somewhere, I can dig that up if interested.

**Comment by manovotn** [comment]
> @manovotn my implementation of these SPIs for Weld is in https://github.com/Ladicek/weld-core/commits/new-tck-spi, feel free to steal that :-) I also have an implementation of these SPIs for ArC on a branch somewhere, I can dig that up if interested.

Thanks but I already have my own draft.
Later today I'll add the `Contextuals` impl to it as well and once I get a pass, I will add a green stamp here.

**Review by manovotn — APPROVED** [review]

**Pull request merged**
