### PR TITLE
Add Support for Selenium Tests

### PR DESCRIPTION
**Pull request by brideck**
- Adds Selenium implementation for Faces Ajax test

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
@manovotn @Ladicek can you take a look at the PR?

**Review by Emily-Jiang — APPROVED** [review]
LGTM

**Comment by Emily-Jiang** [comment]
Any other review comments @manovotn @Ladicek @starksm64 ? Appreciate your feedback. Thanks in advance!

**Comment by pnicolucci** [comment]
@Emily-Jiang some licensing discussion: https://github.com/jakartaee/faces/pull/1794#issuecomment-1453392777

**Comment by pnicolucci** [comment]
@Emily-Jiang @brideck license discussion has finalized: https://github.com/jakartaee/faces/pull/1794 contains the details. This PR is good to go with the Apache copyright header.

**Review by manovotn — COMMENTED** [review]
> I plan to merge this PR tomorrow morning. If you have any objections, please shout asap.

Shouldn't we instead look to remove htmlunit altogether and replace it with selenium tests?
This PR only adds a special-case execution for a singular test.

What are the requirements on impl side to execute such test?
In fact, I think there should be some documentation in terms of requirements for TCK execution and what setup is needed in the [TCK doc](https://jakartaee.github.io/cdi-tck/).

> @starksm64 just a heads up, I will need some help from you to do a service release after this PR is merged.

@Emily-Jiang as a committer you are able to access the Jenkins yourself and run the TCK release job followed up by the maven repo release job. I assume it's even documented somewhere but I have no idea where from the top of my head :)

**Comment by brideck** [comment]
> 
> Shouldn't we instead look to remove htmlunit altogether and replace it with selenium tests? This PR only adds a special-case execution for a singular test.

I don't think that a wholesale technology replacement would be an appropriate change for a TCK service release. The change is designed to provide zero impact to implementations that are already passing the TCK as-is. They would just continue to run with no changes, without adding the new property.

> 
> What are the requirements on impl side to execute such test? In fact, I think there should be some documentation in terms of requirements for TCK execution and what setup is needed in the [TCK doc](https://jakartaee.github.io/cdi-tck/).
 
We could certainly add something to the documentation. Because the logic is the same between the two test implementations, the idea is that someone would only need run one or the other, depending on the modernity of their Faces implementation's javascript support. The changes are that someone running the Selenium tests would need to set the property in their TCK runner and also provide Chrome in their test environment.

**Comment by brideck** [comment]
I've added a note to the documentation explaining why and how you would want to use this new support.

**Comment by manovotn** [comment]
> I don't think that a wholesale technology replacement would be an appropriate change for a TCK service release. The change is designed to provide zero impact to implementations that are already passing the TCK as-is. They would just continue to run with no changes, without adding the new property.

Fair enough, I've created https://github.com/jakartaee/cdi-tck/issues/441 to track the future change.

> I've added a note to the documentation explaining why and how you would want to use this new support.

Thanks!

**Review by manovotn — APPROVED** [review]
I don't fully understand the internals of the problem but the solution is well isolated and doesn't affects other impls testing it, hence my approval :)

**Comment by Emily-Jiang** [comment]
Thank you @manovotn @Ladicek for reviewing this! I will try to follow the instruction and perform a service release shortly.

**Pull request merged**
